#开发环境配置
logging:
  level: #日志级别
    root: info
    com.template.mapper: debug #指定目录级别，优先级大于根目录
spring:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true
      username: root
      password: root
