#生产环境配置
logging:
  level: #日志级别
    root: error #根目录级别
spring:
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp1y69t96pr997nqz0o.mysql.rds.aliyuncs.com:3306/docq?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true
      username: qmw
      password: Qmw81634499
